languageCode = "en"
languageName = "English"
weight = 1
title = "浮生日记"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = ""
  # when turn from light to dark
  # secondaryLogo = ""
  description = "我的树洞"
  copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Terry Tan"
  image = "img/author.jpeg"
  headline = "在通宵的寂静里，我等待着它的意义。"
  bio = "热爱生活，追求智慧。"
  links = [
    { github = "https://github.com/a-fly-fly-bird" },
    # { medium = "https://medium.com/username" },
    # { telegram = "https://t.me/username" },
    { email = "mailto:fuling19.me@gmail.com" },
  ]
